class Element:
    def __init__(self, name, symbol, atomic_number, reactivity, stability, mass, position_x=0, position_y=0, velocity_y=0):
        self.name = name
        self.symbol = symbol
        self.atomic_number = atomic_number
        self.reactivity = reactivity
        self.stability = stability
        self.mass = mass
        self.position_x = position_x
        self.position_y = position_y
        self.velocity_y = velocity_y

    def __str__(self):
        return f"{self.name} ({self.symbol}), Atomic Number: {self.atomic_number}, Reactivity: {self.reactivity}, Stability: {self.stability}, Mass: {self.mass}, Position: ({self.position_x}, {self.position_y}), Velocity: {self.velocity_y}"

periodic_table = [
    Element("Hydrogen", "H", 1, "high", "low", 1.008),
    Element("Helium", "He", 2, "low", "high", 4.0026),
    Element("Lithium", "Li", 3, "high", "low", 6.94),
    Element("Beryllium", "Be", 4, "moderate", "high", 9.0122),
    Element("Boron", "B", 5, "moderate", "high", 10.81),
    Element("Carbon", "C", 6, "high", "high", 12.011),
    Element("Nitrogen", "N", 7, "high", "high", 14.007),
    Element("Oxygen", "O", 8, "very high", "low", 15.999),
    Element("Fluorine", "F", 9, "very high", "low", 18.998),
    Element("Neon", "Ne", 10, "low", "high", 20.180),
    Element("Sodium", "Na", 11, "high", "low", 22.990),
    Element("Magnesium", "Mg", 12, "moderate", "high", 24.305),
    Element("Aluminium", "Al", 13, "moderate", "high", 26.982),
    Element("Silicon", "Si", 14, "moderate", "high", 28.085),
    Element("Phosphorus", "P", 15, "moderate", "high", 30.974),
    Element("Sulfur", "S", 16, "moderate", "high", 32.06),
    Element("Chlorine", "Cl", 17, "high", "low", 35.45),
    Element("Argon", "Ar", 18, "low", "high", 39.948),
    Element("Potassium", "K", 19, "high", "low", 39.098),
    Element("Calcium", "Ca", 20, "moderate", "high", 40.078),
    Element("Scandium", "Sc", 21, "moderate", "high", 44.956),
    Element("Titanium", "Ti", 22, "moderate", "high", 47.867),
    Element("Vanadium", "V", 23, "moderate", "high", 50.942),
    Element("Chromium", "Cr", 24, "moderate", "high", 51.996),
    Element("Manganese", "Mn", 25, "moderate", "high", 54.938),
    Element("Iron", "Fe", 26, "moderate", "high", 55.845),
    Element("Cobalt", "Co", 27, "moderate", "high", 58.933),
    Element("Nickel", "Ni", 28, "moderate", "high", 58.693),
    Element("Copper", "Cu", 29, "moderate", "high", 63.546),
    Element("Zinc", "Zn", 30, "moderate", "high", 65.38),
    Element("Gallium", "Ga", 31, "moderate", "high", 69.723),
    Element("Germanium", "Ge", 32, "moderate", "high", 72.63),
    Element("Arsenic", "As", 33, "moderate", "high", 74.922),
    Element("Selenium", "Se", 34, "moderate", "high", 78.971),
    Element("Bromine", "Br", 35, "high", "low", 79.904),
    Element("Krypton", "Kr", 36, "low", "high", 83.798),
    Element("Rubidium", "Rb", 37, "high", "low", 85.468),
    Element("Strontium", "Sr", 38, "moderate", "high", 87.62),
    Element("Yttrium", "Y", 39, "moderate", "high", 88.906),
    Element("Zirconium", "Zr", 40, "moderate", "high", 91.224),
    Element("Niobium", "Nb", 41, "moderate", "high", 92.906),
    Element("Molybdenum", "Mo", 42, "moderate", "high", 95.95),
    Element("Technetium", "Tc", 43, "moderate", "high", 98),
    Element("Ruthenium", "Ru", 44, "moderate", "high", 101.07),
    Element("Rhodium", "Rh", 45, "moderate", "high", 102.91),
    Element("Palladium", "Pd", 46, "moderate", "high", 106.42),
    Element("Silver", "Ag", 47, "moderate", "high", 107.87),
    Element("Cadmium", "Cd", 48, "moderate", "high", 112.41),
    Element("Indium", "In", 49, "moderate", "high", 114.82),
    Element("Tin", "Sn", 50, "moderate", "high", 118.71),
    Element("Antimony", "Sb", 51, "moderate", "high", 121.76),
    Element("Tellurium", "Te", 52, "moderate", "high", 127.60),
    Element("Iodine", "I", 53, "high", "low", 126.90),
    Element("Xenon", "Xe", 54, "low", "high", 131.29),
    Element("Caesium", "Cs", 55, "high", "low", 132.91),
    Element("Barium", "Ba", 56, "moderate", "high", 137.33),
    Element("Lanthanum", "La", 57, "moderate", "high", 138.91),
    Element("Cerium", "Ce", 58, "moderate", "high", 140.12),
    Element("Praseodymium", "Pr", 59, "moderate", "high", 140.91),
    Element("Neodymium", "Nd", 60, "moderate", "high", 144.24),
    Element("Promethium", "Pm", 61, "moderate", "high", 145),
    Element("Samarium", "Sm", 62, "moderate", "high", 150.36),
    Element("Europium", "Eu", 63, "moderate", "high", 151.96),
    Element("Gadolinium", "Gd", 64, "moderate", "high", 157.25),
    Element("Terbium", "Tb", 65, "moderate", "high", 158.93),
    Element("Dysprosium", "Dy", 66, "moderate", "high", 162.50),
    Element("Holmium", "Ho", 67, "moderate", "high", 164.93),
    Element("Erbium", "Er", 68, "moderate", "high", 167.26),
    Element("Thulium", "Tm", 69, "moderate", "high", 168.93),
    Element("Ytterbium", "Yb", 70, "moderate", "high", 173.04),
    Element("Lutetium", "Lu", 71, "moderate", "high", 174.97),
    Element("Hafnium", "Hf", 72, "moderate", "high", 178.49),
    Element("Tantalum", "Ta", 73, "moderate", "high", 180.95),
    Element("Tungsten", "W", 74, "moderate", "high", 183.84),
    Element("Rhenium", "Re", 75, "moderate", "high", 186.21),
    Element("Osmium", "Os", 76, "moderate", "high", 190.23),
    Element("Iridium", "Ir", 77, "moderate", "high", 192.22),
    Element("Platinum", "Pt", 78, "moderate", "high", 195.08),
    Element("Gold", "Au", 79, "moderate", "high", 196.97),
    Element("Mercury", "Hg", 80, "moderate", "high", 200.59),
    Element("Thallium", "Tl", 81, "moderate", "high", 204.38),
    Element("Lead", "Pb", 82, "moderate", "high", 207.2),
    Element("Bismuth", "Bi", 83, "moderate", "high", 208.98),
    Element("Polonium", "Po", 84, "moderate", "high", 209),
    Element("Astatine", "At", 85, "moderate", "high", 210),
    Element("Radon", "Rn", 86, "low", "high", 222),
    Element("Francium", "Fr", 87, "high", "low", 223),
    Element("Radium", "Ra", 88, "moderate", "high", 226),
    Element("Actinium", "Ac", 89, "moderate", "high", 227),
    Element("Thorium", "Th", 90, "moderate", "high", 232.04),
    Element("Protactinium", "Pa", 91, "moderate", "high", 231.04),
    Element("Uranium", "U", 92, "moderate", "high", 238.03),
    Element("Neptunium", "Np", 93, "moderate", "high", 237),
    Element("Plutonium", "Pu", 94, "moderate", "high", 244),
    Element("Americium", "Am", 95, "moderate", "high", 243),
    Element("Curium", "Cm", 96, "moderate", "high", 247),
    Element("Berkelium", "Bk", 97, "moderate", "high", 247),
    Element("Californium", "Cf", 98, "moderate", "high", 251),
    Element("Einsteinium", "Es", 99, "moderate", "high", 252),
    Element("Fermium", "Fm", 100, "moderate", "high", 257),
    Element("Mendelevium", "Md", 101, "moderate", "high", 258),
    Element("Nobelium", "No", 102, "moderate", "high", 259),
    Element("Lawrencium", "Lr", 103, "moderate", "high", 262),
    Element("Rutherfordium", "Rf", 104, "moderate", "high", 267),
    Element("Dubnium", "Db", 105, "moderate", "high", 270),
    Element("Seaborgium", "Sg", 106, "moderate", "high", 271),
    Element("Bohrium", "Bh", 107, "moderate", "high", 270),
    Element("Hassium", "Hs", 108, "moderate", "high", 277),
    Element("Meitnerium", "Mt", 109, "moderate", "high", 276),
    Element("Darmstadtium", "Ds", 110, "moderate", "high", 281),
    Element("Roentgenium", "Rg", 111, "moderate", "high", 282),
    Element("Copernicium", "Cn", 112, "moderate", "high", 285),
    Element("Nihonium", "Nh", 113, "moderate", "high", 286),
    Element("Flerovium", "Fl", 114, "moderate", "high", 289),
    Element("Moscovium", "Mc", 115, "moderate", "high", 290),
    Element("Livermorium", "Lv", 116, "moderate", "high", 293),
    Element("Tennessine", "Ts", 117, "moderate", "high", 294),
    Element("Oganesson", "Og", 118, "moderate", "high", 294)
]

def get_periodic_table():
    return periodic_table
